#!/bin/zsh

mkdir binutils-build
mkdir binutils-install
cd binutils-build
../binutils-${V_BINUTILS}/configure \
    --host=${FRCHOSTTARGET} \
    --prefix=${FRCPREFIX} \
    --target=arm-frc${V_YEAR}-linux-gnueabi \
    "--with-pkgversion=GNU Binutils for FRC ${V_YEAR}" \
    --enable-poison-system-directories \
    --with-sysroot=${FRCPREFIX}/arm-frc${V_YEAR}-linux-gnueabi \
    --enable-plugins \
    --disable-nls \
    --enable-lto \
    --with-build-sysroot=${FRCPREFIX}/arm-frc${V_YEAR}-linux-gnueabi \
    --disable-werror
make -j3
DESTDIR=$PWD/../binutils-install make install
cd ../binutils-install
