name: CI

on: [pull_request, push]

jobs:
  build-linux:
    name: "Build - Linux"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ./build-linux-tgz.sh
      - uses: actions/upload-artifact@v2
        with:
          name: Linux
          path: FRC-*-Linux*.tar.gz

  build-windows:
    name: "Build - Windows"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ./build-windows.sh
      - uses: actions/upload-artifact@v2
        with:
          name: Windows
          path: FRC-*-Windows*.zip

  build-macos:
    name: "Build - macOS"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ./build-mac.sh
      - name: Import Developer ID Certificate
        uses: wpilibsuite/import-signing-certificate@v1
        with:
          certificate-data: ${{ secrets.APPLE_CERTIFICATE_DATA }}
          certificate-passphrase: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          keychain-password: ${{ secrets.APPLE_KEYCHAIN_PASSWORD }}
        if: |
          github.repository_owner == 'wpilibsuite' &&
          (github.ref == 'refs/heads/2021' || startsWith(github.ref, 'refs/tags/v'))
      - run: ./codesign.sh ${{ secrets.APPLE_DEVELOPER_ID }}
        if: |
          github.repository_owner == 'wpilibsuite' &&
          (github.ref == 'refs/heads/2021' || startsWith(github.ref, 'refs/tags/v'))
      - uses: actions/upload-artifact@v2
        with:
          name: macOS
          path: mac/*Toolchain*.tar.gz

  release:
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "**/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
